project:
  type: website
  title: "Spatial Data Analysis"
  resources:
    - "*/data/*"
    - environment.yml
    - "*/slides/*"
  output-dir: ./docs

lang: en

execute:
  freeze: false
  cache: true

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: assets/styles.css
    toc: true
    smooth-scroll: true
    highlight-style: atom-one
    bibliography: assets/references.bib

website:
  repo-url: https://github.com/sjsrey/g358s24/
  favicon: assets/favicon.png
  repo-actions: [issue]
  twitter-card: false
  page-navigation: true
  page-footer:
    center: "Course material by [Sergio Rey](https://sergerey.org). Available under [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)."
  search:
    location: sidebar
    type: overlay
  sidebar:
    style: floating
    collapse-level: 1
    logo: assets/logo.svg
    tools:
      - icon: github
        href: https://github.com/sjsrey/g358s24
    contents:
      - section: "Syllabus"
        contents:
          - syllabus.qmd
      - text: "---"
      - section: "Week 1 1/18"
        contents:
          - week-01/01-introduction.qmd

      - section: "Week 2 1/23, 1/25"
        contents:
          - week-02/files-dirs.qmd
      
      - section: "Week 3 1/30, 2/01"
        contents:
          - week-03/python_intro.ipynb
          - week-03/python_concepts.ipynb

      - section: "Week 4 2/06, 2/08"
        contents:
          - week-04/scripts_and_functions.ipynb
          - week-04/import_demo.ipynb
          - week-04/distances.qmd

      - section: "Week 5 2/13, 2/15"
        contents:
          - week-05/pandas_intro.ipynb

      - section: "Week 6 2/20"
        contents:
          - week-06/geopandas.ipynb
